### ISSUE TITLE
Compatibility with Thunderbird 68+ / web extensions

### ISSUE THREAD

**Issue by gom-sh** [kee-org/keebird#23] opened 2019-11-05 15:40 UTC
Thunderbird 68 got the same interface for extensions as firefox since version 57+ had (web extensions). Therefore keebird won't work with Thunderbird any more. Please document this behaviour and point to alternatives or reimplement keebird for webextenions.

Thanks for all you work.

**Comment by dlech** [comment] 2019-11-05 16:30
Duplicate of #18

**Closed by dlech** 2019-11-05 16:30 UTC
Labels: duplicate
